delete:
  description: Remove a user role from a user. User needs to have `users.manage`
    permission in order to call this API successfully.
  tags:
    - User Role Management
  security:
    - AuthenticationToken: []
  parameters:
    - name: user_id
      in: path
      description: The user to be remove user role for.
      schema:
        $ref: "../../../../../../components/schemas/User.yml#/properties/id"
      required: true
    - name: user_role_id
      in: path
      description: The user role to be removed from the user.
      schema:
        $ref: "../../../../../../components/schemas/UserRole.yml#/properties/id"
      required: true
  responses:
    "200":
      description: User role removed to user successfully.
      headers:
        Set-Cookie:
          description: Renewed authentication token, if the user old token is
            about to expire.
          schema:
            $ref: "../../../../../../components/schemas/Token.yml"
    "401":
      description: Failed to remove user role from user because the user is not
        logged in.
    "403":
      description: Failed to remove user role from user because the user does
        not have the necessary permission.
    "404":
      description:
        Failed to remove user role from user because user with user_id
        or user role with user_role_id does not exist.
    "409":
      description:
        Failed to remove user role from user because user with user_id
        does not have user role with user_role_id.
